[features]
seeds = false
skip-lint = false

[programs.devnet]
booty_contract = "HzAWxmoXNewwrJRwUY39Xjnoh25hAiQBnPgcfKYGbmxi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
